n1 = int(input('Digite o 1° valor: '))
n2 = int(input('Digite o 2° valor: '))
n3 = int(input('Digite o 3° valor: '))
soma = (n1 ** 2) + (n2 ** 2) + (n3 ** 2)
print(f'A soma dos quadrados dos valores são {soma}!')